version: '3'

services:
  local-postgres-compose:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "demo_magalu_database"
    ports:
      - "5432:5432"
    networks:
      - demo-project-network
  rabbit-mq:
    image: rabbitmq:3.9-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - demo-project-network
  simulador-oracleebs:
    image: tlrferreira83/demo-magalu:simulador-oracleebs
    container_name: simulador-oracleebs-container
    ports:
      - "8081:8081"
    networks:
      - demo-project-network

networks:
  demo-project-network:
    driver: bridge