spring:
  application:
    name: demo-magalu
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: "jdbc:postgresql://localhost:5432/demo_magalu_database"
    username: "postgres"
    password: "example"
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mq:
  queues:
    email-queue: default-email-queue

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR